# Generated by Django 3.0.2 on 2021-03-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ICohm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PartNumber', models.BigIntegerField()),
                ('Description', models.CharField(max_length=40)),
                ('OhmValue', models.PositiveIntegerField()),
                ('Tolerance', models.FloatField()),
                ('PackType', models.IntegerField()),
                ('VoltageRating', models.IntegerField()),
                ('Height_mm', models.FloatField()),
            ],
        ),
    ]
