# Generated by Django 3.1.3 on 2021-04-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PdmQuery', '0002_auto_20210331_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icohm',
            name='Height_mm',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='icohm',
            name='Tolerance',
            field=models.FloatField(),
        ),
    ]
